# Archivo: _quarto.yml
project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - datos.qmd
    - codigos.qmd
    - proyectos.qmd
    - data_principal.qmd
    - data_secundaria.qmd
    - "labs/*.qmd"

website:
  title: ""
  site-url: https://fen-uah.github.io/lab-econometria/
  description: "Repositorio de datos, códigos y proyectos de estudiantes"

  navbar:
    logo: img/logo.png
    left:
      - text: "Inicio"
        href: index.qmd

      - text: "Material de Estudio"
        href: codigos.qmd
        menu:
          - text: "Econometría - Mención Economía"
            href: eco_eco.qmd
            target: _blank
          - text: "Econometría para la Gestón - Mención Administración "
            href: eco_epg.qmd
            target: _blank

      - text: "Datos"
        href: datos.qmd
        menu:
          - text: "Data Principal"
            href: data_principal.qmd
            target: _blank
          - text: "Data Secundaria"
            href: data_secundaria.qmd
            target: _blank

      - text: "Proyectos"
        href: proyectos.qmd

  page-footer:
    left: "© 2025 FEN-UAH"
    right: "Sitio desarrollado con Quarto"

format:
  html:
    css: styles.css
    toc: true
    smooth-scroll: true
    grid:
      body-width: 900px
      gutter-width: 1.2em
resources:
  - js/open_links_newtab.